plugins {
  id 'java-library'
  id 'io.spring.dependency-management'
}

dependencyManagement {
  imports {
    mavenBom "org.springframework.boot:spring-boot-dependencies:3.5.0"
  }
}

dependencies {
  api 'org.springframework.boot:spring-boot-starter-data-jpa'
  api 'jakarta.validation:jakarta.validation-api'
  runtimeOnly 'com.mysql:mysql-connector-j'
}
